# Generated by Django 3.2 on 2025-11-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_from',
            field=models.BooleanField(default=False, help_text='Если включено — перед ценой будет написано «от»', verbose_name='Цена «от»'),
        ),
    ]
